---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: 12:00
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
      time: 12:00
