---
changelog:
  exclude:
    labels:
      - ignore-for-release
      - wontfix
      - invalid
      - duplicate
    authors:
      - pre-commit-ci
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Security Changes 🩹
      labels:
        - security
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Changes
      labels:
        - "*"
