---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - '--allow-multiple-documents'
      - id: check-json
      - id: check-added-large-files
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.7.0.1
    hooks:
      - id: shfmt
        args:
          - "--binary-next-line"
          - "--case-indent"
          - "--indent"
          - "4"
          - "--space-redirects"
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args:
          - '--ignore'
          - 'DL3007'
          - '--ignore'
          - 'DL3008'
          - '--ignore'
          - 'DL3013'
          - '--ignore'
          - 'DL3059'
        types: [file]
        files: "^tests/Dockerfile_.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        additional_dependencies:
          - pytest
          - pytest-shell-utilities
          - requests
          - types-requests
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - pytest-shell-utilities
          - requests
          - types-requests
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: local
    hooks:
      - id: permission-check
        name: check permissions using pytest
        entry: pytest -v -s -k test_permissions tests/test_00_minimal.py
        language: python
        pass_filenames: false
        additional_dependencies:
          - pytest
          - pytest-shell-utilities
          - requests
