FROM		ubuntu:latest
COPY		tests/requirements.txt /requirements.txt
COPY		helper/install_deps.sh /install_deps.sh
# hadolint ignore=DL3018
ENV		DEBIAN_FRONTEND=noninteractive
RUN		apt-get update \
		&& apt-get install --no-install-recommends -q --yes \
			curl \
			build-essential \
			python3-pip \
			python3-dev \
			sudo \
			vim \
		&& pip install --no-cache-dir -qr /requirements.txt \
		&& rm -f /requirements.txt \
		&& install -d -o root -g root /pytest_cache \
		&& /install_deps.sh \
		&& rm -f /install_deps.sh \
		&& apt-get clean \
		&& apt-get -y autoremove \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR		/app
ENTRYPOINT	["pytest", "-v", "-s", "-o", "cache_dir=/pytest_cache", "--color", "yes"]
