FROM		ubuntu:latest
COPY		tests/requirements.txt /requirements.txt
COPY		helper/install_deps.sh /install_deps.sh
RUN		install -d -o root -g root /pytest_cache
# hadolint ignore=DL3018
ENV		DEBIAN_FRONTEND=noninteractive
ENV		HTTPS_SUPPORT=true
RUN		apt-get update \
		&& apt-get install --no-install-recommends -q --yes \
			curl \
			build-essential \
			python3-pip \
			python3-dev \
			sudo \
			vim \
		&& apt-get clean \
		&& apt-get -y autoremove \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN		pip install --no-cache-dir -r /requirements.txt --break-system-packages \
		&& rm -f /requirements.txt
RUN		/install_deps.sh \
		&& rm -f /install_deps.sh
WORKDIR		/app
ENTRYPOINT	["pytest", "-v", "-s", "-o", "cache_dir=/pytest_cache", "--color", "yes"]
