FROM		alpine:latest
COPY		tests/requirements.txt /tests/requirements.txt
COPY		helper/install_deps.sh /helper/install_deps.sh
RUN		install -d -o root -g root /pytest_cache
# hadolint ignore=DL3018
RUN		apk add --no-cache --quiet sudo
ENV		CI=true
RUN		/helper/install_deps.sh \
		&& rm -rf /helper/
WORKDIR		/app
ENTRYPOINT	["/.venv/bin/pytest", "-v", "-s", "-o", "cache_dir=/pytest_cache", "--color", "yes"]
