FROM		openwrt/rootfs:x86-64-23.05.3
RUN		mkdir /pytest_cache && chown root:root /pytest_cache
COPY		tests/requirements.txt /tests/requirements.txt
COPY		helper/install_deps.sh /helper/install_deps.sh
ENV		CI=true
RUN		/helper/install_deps.sh \
		&& rm -rf /helper/
RUN		opkg install \
			sudo \
			vim-full
RUN	 	rm -rf /tmp/* || true
WORKDIR		/app
ENTRYPOINT	["/.venv/bin/pytest", "-v", "-s", "-o", "cache_dir=/pytest_cache", "--color", "yes"]
