FROM		ubuntu:latest
COPY		tests/requirements.txt /tests/requirements.txt
COPY		helper/install_deps.sh /helper/install_deps.sh
RUN		install -d -o root -g root /pytest_cache
RUN		useradd -U -G sudo test_run
ENV		DEBIAN_FRONTEND=noninteractive
ENV		HTTPS_SUPPORT=true
ENV		CI=true
RUN		/helper/install_deps.sh \
		&& rm -rf /helper/
RUN		apt-get install --no-install-recommends -q --yes \
			sudo \
			vim \
		&& echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/nopw \
		&& apt-get clean \
		&& apt-get -y autoremove \
		&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR		/app
USER		test_run
ENTRYPOINT	["sudo", "/.venv/bin/pytest", "-v", "-s", "-o", "cache_dir=/pytest_cache", "--color", "yes"]
